ALTER TABLE `%PREFIX%resdata` ADD `ico` VARCHAR( 15 ) NULL COMMENT 'res ico';
INSERT INTO `%PREFIX%plugins` (`name`, `file`, `active`) VALUES ('fblog', 'fb/fb-log', 0);
ALTER TABLE `%PREFIX%plugins` ADD `group` VARCHAR( 15 ) NULL ;
UPDATE `%PREFIX%conf` SET `sge_ver` =  '040' WHERE CONVERT( `sge_ver` USING utf8 ) =  '039' LIMIT 1 ;
ALTER TABLE `%PREFIX%uque` CHANGE `end` `end` INT( 15 ) NOT NULL DEFAULT '0';
ALTER TABLE `%PREFIX%ally` CHANGE `name` `name` VARCHAR( 25 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL , CHANGE `desc` `desc` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%builds` CHANGE `func` `func` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%city` CHANGE `name` `name` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%cmsg` CHANGE `username` `username` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,CHANGE `msg` `msg` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,CHANGE `color` `color` VARCHAR( 1 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `%PREFIX%conf` CHANGE `news1` `news1` TINYTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL , CHANGE `sge_ver` `sge_ver` VARCHAR( 5 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '039';
ALTER TABLE `%PREFIX%market` CHANGE `resrqnt` `resrqnt` INT( 15 ) NOT NULL COMMENT 'quantity reqested';
ALTER TABLE `%PREFIX%plugins` CHANGE `name` `name` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `file` `file` VARCHAR( 11 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '.php',CHANGE `group` `group` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `%PREFIX%races` CHANGE `rname` `rname` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'x',CHANGE `rdesc` `rdesc` TINYTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `img` `img` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'null.gif';
ALTER TABLE `%PREFIX%resdata` CHANGE `name` `name` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `ico` `ico` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT 'res ico';
ALTER TABLE `%PREFIX%rulers` CHANGE `text` `text` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%tutorial` CHANGE `tittle` `tittle` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `body` `body` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%t_builds` CHANGE `name` `name` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'barraks',CHANGE `func` `func` VARCHAR( 35 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'barraks',CHANGE `img` `img` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'null.gif',CHANGE `desc` `desc` TINYTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `%PREFIX%t_research` CHANGE `name` `name` VARCHAR( 25 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `img` `img` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'null.gif';
ALTER TABLE `%PREFIX%t_unt` CHANGE `name` `name` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `img` `img` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'null.gif',CHANGE `desc` `desc` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `type` `type` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT 'type of unit: archer etc.';
ALTER TABLE `%PREFIX%umsg` CHANGE `mtit` `mtit` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,CHANGE `text` `text` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `%PREFIX%users` CHANGE `username` `username` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `password` `password` VARCHAR( 32 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',CHANGE `email` `email` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,CHANGE `active` `active` VARCHAR( 2 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ,CHANGE `lang` `lang` VARCHAR( 3 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'en' COMMENT 'laguage';
ALTER TABLE `%PREFIX%ally` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%builds` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%cmsg` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%conf` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%plugins` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%races` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%resdata` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%tutorial` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%t_builds` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%t_research` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%t_unt` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%umsg` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%users` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `%PREFIX%map` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER DATABASE DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
