ALTER TABLE `%PREFIX%resdata` CHANGE `start` `start` INT( 6 ) NOT NULL DEFAULT '100';
ALTER TABLE `%PREFIX%races` CHANGE `id` `id` SMALLINT( 10 ) NOT NULL AUTO_INCREMENT;
ALTER TABLE `%PREFIX%umsg` CHANGE `id` `id` INT( 10 ) NOT NULL AUTO_INCREMENT;
UPDATE `%PREFIX%conf` SET `sge_ver` =  '042' WHERE CONVERT( `sge_ver` USING utf8 ) =  '041' LIMIT 1 ;