 CREATE TABLE `%PREFIX%umsg` (
`id` INT( 15 ) NOT NULL AUTO_INCREMENT ,
`from` INT( 15 ) NOT NULL ,
`to` INT( 15 ) NOT NULL ,
`text` TEXT NOT NULL ,
PRIMARY KEY ( `id` )
) ENGINE = MYISAM;

ALTER TABLE `%PREFIX%umsg` ADD `read` BOOL NOT NULL DEFAULT '0';

ALTER TABLE `%PREFIX%users` ADD `banned` BOOL NOT NULL DEFAULT '0' AFTER `active` ;

 ALTER TABLE `%PREFIX%users` CHANGE `timestamp` `timestamp_reg` INT( 11 ) NOT NULL ,
CHANGE `sent_on` `last_log` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

 CREATE TABLE `%PREFIX%ally` (
`id` INT( 15 ) NOT NULL AUTO_INCREMENT ,
`name` VARCHAR( 25 ) NOT NULL ,
`owner` INT( 15 ) NOT NULL DEFAULT '0',
PRIMARY KEY ( `id` )
) ENGINE = MYISAM;

ALTER TABLE `%PREFIX%users` ADD `ally_id` INT( 15 ) NOT NULL DEFAULT '0' AFTER `capcity` ;

UPDATE `%PREFIX%conf` SET `sge_ver` =  '014' WHERE CONVERT( `sge_ver` USING utf8 ) =  '013' LIMIT 1 ;